### PR TITLE
Misc

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Misc changes:

* Format codebase
* Fix 3 clippy lints

### CODE REVIEW

**Comment by Profpatsch** [comment]
hello

**Comment by matthiasbeyer** [comment]
Hi! :smile:

**Comment by matthiasbeyer** [comment]
Care to merge these patches?

**Comment by Profpatsch** [comment]
> Care to merge these patches?

just a contributor, sorry :)

**Comment by matthiasbeyer** [comment]
okay, well then I'll wait.

**Review by untitaker — APPROVED** [review]

**Comment by untitaker** [comment]
Thanks!

**Pull request merged**
